# Generated by Django 5.0.1 on 2024-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_options_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'employee'), ('customer', 'customer'), ('manager', 'manager'), ('supervisor', 'supervisor')], default='customer', max_length=10, verbose_name='user type'),
        ),
    ]
