# Generated by Django 4.2.9 on 2024-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_day',
            field=models.DateField(blank=True, help_text='بین تاریخ ها را با - پر نمایید.', null=True, verbose_name='birth day'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.PositiveSmallIntegerField(verbose_name='national code'),
        ),
    ]
