# Generated by Django 4.2.9 on 2024-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='national code'),
        ),
    ]
