# Generated by Django 4.2.7 on 2024-01-12 13:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[product.models.Discount.amount_check]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('percent', 'PERCENT'), ('number', 'number')], default='percent', max_length=10),
        ),
    ]
