# Generated by Django 4.2.7 on 2024-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_dis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
