# Generated by Django 4.2.7 on 2024-01-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_discount_amount_alter_discount_max_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_dis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
