# Generated by Django 4.2.7 on 2024-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_discount_max_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='max_dis',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('percent', 'PERCENT'), ('number', 'NUMBER')], default='percent', max_length=10),
        ),
    ]
