# Generated by Django 5.0.1 on 2024-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_discount_max_dis_alter_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
    ]
