# Generated by Django 5.0.1 on 2024-01-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_discount_created_at_remove_discount_delete_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mojoudi',
            new_name='inventory',
        ),
    ]
