# Generated by Django 4.2.7 on 2024-01-14 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_discount_created_at_discount_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 12, 55, 46, 666574, tzinfo=datetime.timezone.utc)),
        ),
    ]
