# Generated by Django 4.2.7 on 2024-01-14 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 40, 12, 61088, tzinfo=datetime.timezone.utc)),
        ),
    ]
