# Generated by Django 4.2.7 on 2024-01-15 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_discount_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 10, 56, 2, 147368, tzinfo=datetime.timezone.utc)),
        ),
    ]
