# Generated by Django 5.0.1 on 2024-01-20 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_discount_expire_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 0, 26, 25, 756452, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
