# Generated by Django 4.2.7 on 2024-01-21 09:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 17, 6, 29, 254303, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products', verbose_name='image'),
            preserve_default=False,
        ),
    ]
