# Generated by Django 5.0.1 on 2024-01-25 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_like_created_at_like_delete_at_like_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 10, 48, 13, 66708, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
