# Generated by Django 4.2.7 on 2024-01-31 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_category_created_at_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 7, 44, 6, 345221, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
