# Generated by Django 4.2.7 on 2024-01-31 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 7, 48, 50, 680848, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
