# Generated by Django 4.2.7 on 2024-02-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 14, 1, 24, 758470, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
