# Generated by Django 5.0.1 on 2024-02-05 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 7, 6, 47, 74557, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
