# Generated by Django 5.0.1 on 2024-02-07 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_discount_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expire',
            field=models.DateField(default=datetime.datetime(2024, 2, 9, 11, 48, 48, 751455, tzinfo=datetime.timezone.utc), verbose_name='expire'),
        ),
    ]
