# Generated by Django 4.2.7 on 2024-01-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_price_remove_orderitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
