# Generated by Django 4.2.7 on 2024-01-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
